### ISSUE TITLE
get 401 error when sending request to yahoo gemini api

### ISSUE THREAD

**Issue by smthxwolf** [josuebrunel/yahoo-oauth#43] opened 2015-12-16 03:05 UTC
hello, this is the best python lib i have found to access yahoo oauth2. 
i have get access token using this lib. but when i tried to send request to yahoo gemini api, i always got an 401 Response

here is the output:

``` shell
[2015-12-16 10:55:11,472 DEBUG] [yahoo_oauth.yahoo_oauth.__init__] Checking 
[2015-12-16 10:55:11,477 DEBUG] [yahoo_oauth.yahoo_oauth.token_is_valid] ELAPSED TIME : 164795.42615
[2015-12-16 10:55:11,477 DEBUG] [yahoo_oauth.yahoo_oauth.token_is_valid] TOKEN HAS EXPIRED
[2015-12-16 10:55:11,478 DEBUG] [yahoo_oauth.yahoo_oauth.refresh_access_token] REFRESHING TOKEN
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.login.yahoo.com
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
[2015-12-16 10:55:13,310 DEBUG] [yahoo_oauth.yahoo_oauth.token_is_valid] ELAPSED TIME : 1.83199310303
[2015-12-16 10:55:13,311 DEBUG] [yahoo_oauth.yahoo_oauth.token_is_valid] TOKEN IS STILL VALID
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.admanager.yahoo.com
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
<Response [401]>
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.admanager.yahoo.com
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
<Response [401]>
None
```

here is my code:

``` python
from yahoo_oauth import OAuth2
import requests
def get_simple_report(min_date, max_date):
    yahoo_oauth = OAuth2(None, None, from_file='./config/yahooads.ini')
    if not yahoo_oauth.token_is_valid():
            yahoo_oauth.refresh_access_token()
    access_token = yahoo_oauth.access_token
    advertiser_id = 1151514
    # get campaign list
    campaign_end_point = "https://api.admanager.yahoo.com/v1/rest/campaign/"
    payload_dict = {
            "advertiserId":advertiser_id,
            "mr":2
            }
    header = {'Authorization': 'Bearer ' + access_token,'Accept': 'application/json','Content-Type': 'application/json'}
    response = requests.get(campaign_end_point, data=payload_dict, headers = header)
    print response

    response = yahoo_oauth.session.put(campaign_end_point, params=payload_dict)
    print response
```

i also tried rauth but got the same error. 

could you pls help me with it? thanks

**Comment by josuebrunel** [comment] 2015-12-16 11:05
Hello @jiangchunyang ,
1. First of all, i don't think this lib support ***.ini*** file, but this might the opportunity to do so. You can submit a patch if you want :wink: 
2. I don't think you need to use ***requests*** since it's already encapsulated in the lib via **rauth**. 

```python
from yahoo_oauth import OAuth2

def get_simple_report(min_data, max_date):
    yahoo_oauth = OAuth2(None, None, from_file='./config/yahooads.json')
    # No need to check token validity, the lib auto check for you. Sorry the doc is kind of misleading
    advertiser_id = 1151514
    campaign_end_point = "https://api.admanager.yahoo.com/v1/rest/campaign/"
    payload_dict = {
            "advertiserId":advertiser_id,
            "mr":2
            }
    response = yahoo_oauth.session.put(campaign_end_point, data=payload_dict)
    print(response.status_code, response.reason)
    return response
```

@jiangchunyang Could you please try this and let me know ?

have a good one

**Comment by jiangchunyang** [comment] 2015-12-17 03:42
hi @josuebrunel, thank you for your quick response. 
i used your suggested codes, but still got 401 response.

/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
(401, 'Authorization Required')

i also google this problem, now i suspect it's not because of the codes. 
i applied an api on this page https://developer.yahoo.com/gemini/apply.html but haven't got any response mail yet. 
however i managed to access this page https://developer.yahoo.com/apps/create/ and created an app and got consumer key & secret, which i'm using to get gemini report. 
is it the reason?
thanks

**Comment by josuebrunel** [comment] 2015-12-17 08:26
@jiangchunyang ok i see, 
**consumer key** and **consumer secret** are **required** to make the lib work 
Once you have them, put them in a *json* or *yaml* file 

example (yahooads.json)
```json
{
    "consumer_key": "your consumer key here",
    "consumer_secret": "your consumer sercret here"
}
```

then in your code 
```python
from yahoo_oauth import OAuth2

oauth = OAuth2(None, None, from_file='config/yahooads.json')
....
.oauth.session.put(campaign_end_point, data=payload_dict)
```
Something like this. If it still doesn't work i'll try to provide better example within the weekend

**Comment by jiangchunyang** [comment] 2015-12-17 09:54
many thanks for your time. 
just one more question which confused me these days, is it required that the access token (or some other information) is put into the request header, if i use rauth or urllib to send request to yahoo's api?

**Comment by josuebrunel** [comment] 2015-12-17 10:27
@jiangchunyang , yeah you can check these lines https://github.com/josuebrunel/yahoo-oauth/blob/master/yahoo_oauth/yahoo_oauth.py#L147-L156. **yahoo_oauth** does it for you already.

**Comment by jiangchunyang** [comment] 2015-12-19 08:54
hello @josuebrunel 
today i tried to access yahoo fantasy sport api, which i granted all the permissions. 
here is the access token information:

{
    "access_token": "4RdZFeyd5h_2gpyRDwsRVgoP6pMmv7cmiTxvLWxspLxFFBxG7eOpC2ZJESNoeysj2iGBA5vCrA22H3t0G2pbsjylB3hLV110NlxSsBo96RrVbPWJTo.4nRa_dY59Q2HhT3gfV.GUtLI7hWTMPplmCi_EFXzf1Wq024A1RvffoZq7Smu2mzqJWTLj9Zz4Nw6EBW6kb9Iod3XfMb3a4aEXKFlbwEugU7OreEx_pUJPdZ2FwO_9neA4_.kuoTlZwuRuHnbRaPcY..FdSN30WmcPckrbd5xF.f4.pNSCaL3V6WXLiVPxnQgYdlQQk6uh.GXZHLdyWe1czbx40XaPuTZkudYHm.xipJtKMppsvHE.1pOQD_r_bMLsspwwYKxRcUcwAq2GItiipXbMWNF9gq9U5F8GVrJq1kUhYueoFXvuTQBcZLkhbjE6uBjVwnOwHy9lSa._Vf9wcsGDCI9vLayjxzFzgtwtXuVB7tjQTb6YvyEfbt.hcu1sMjgGm8LK5_XQQT7UwaFhfXw2Bzb82gnxkKRQgiJ9nMGdWQTX4kWcq8VjSSTdKX_.xrXfheB2QDJG8z6sCHZyUX4Mq1.emEqHXvUG5trZA15nB09p53eB7xdazISsts27dbrRVGz0AWfQdyjPVTRqf8ADNzY_RupkHRH3JYfKuiL6nftLwpFsDgAY5mPpRyBbdaV128YrT5.MxgnrH70ExRDq30TvecC17G9gANfLFva06s.UqjHxUhSKKuQIn0Qsy71gtDPTWJBDUBuFZAUZ6wOgMZ4v6Ck3DMWPyoesk64BUUWCuA--",
    "consumer_key": "dj0yJmk9YnBqUEtEV1ZTM2RSJmQ9WVdrOWNFWndZamhXTkdFbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD02Yw--",
    "consumer_secret": "72e5e5e72d42f6494a02da2c893b502162d8167f",
    "guid": "T5YJGP6ME4VHRZ732ASZ5YRCP4",
    "refresh_token": "AFMZdVZQlnfvA4Yr3w1Skn743QejtgIJP5BF4kxgcmtifcNKtCs-",
    "token_time": 1450514973.39519,
    "token_type": "bearer"
}

but still i get error code 401.
here is the codes:
def get_simple_report(min_data, max_date):
    yahoo_oauth = OAuth2(None, None, from_file='./config/yahooads.json')
    # No need to check token validity, the lib auto check for you. Sorry the doc is kind of misleading

    response = yahoo_oauth.session.get('http://fantasysports.yahooapis.com/fantasy/v2/game/223')
    print(response.status_code, response.reason)
    return response

nothing special. what's wrong with it? thanks

**Comment by josuebrunel** [comment] 2015-12-19 10:24
Hey @jiangchunyang,
First of all, **consumer_key** and **consumer_secret** are private data, so you shouldn't share them. 
I've found the issue. 
**Yahoo Fantasay Sport** doesn't use *OAuth2*, instead it uses **OAuth1**.

```python
>>> from yahoo_oauth import OAuth1
>>> oauth = OAuth1(None, None, from_file='oauth1.json')
[2015-12-19 11:21:18,105 DEBUG] [yahoo_oauth.yahoo_oauth.__init__] Checking 
[2015-12-19 11:21:18,105 DEBUG] [yahoo_oauth.yahoo_oauth.token_is_valid] ELAPSED TIME : 150.253709078
[2015-12-19 11:21:18,105 DEBUG] [yahoo_oauth.yahoo_oauth.token_is_valid] TOKEN IS STILL VALID
>>> response = oauth.session.get('http://fantasysports.yahooapis.com/fantasy/v2/game/223')
>>> response.status_code, response.reason
(200, 'OK')
>>> 
>>> response.content
'<?xml version="1.0" encoding="UTF-8"?>\n<fantasy_content xml:lang="en-US" yahoo:uri="http://fantasysports.yahooapis.com/fantasy/v2/game/223" time="56.034088134766ms" copyright="Data provided by Yahoo! and STATS, LLC" refresh_rate="31" xmlns:yahoo="http://www.yahooapis.com/v1/base.rng" xmlns="http://fantasysports.yahooapis.com/fantasy/v2/base.rng">\n <game>\n  <game_key>223</game_key>\n  <game_id>223</game_id>\n  <name>Football PLUS</name>\n  <code>pnfl</code>\n  <type>full</type>\n  <url>http://football.fantasysports.yahoo.com/f2</url>\n  <season>2009</season>\n  <is_registration_over>1</is_registration_over>\n </game>\n</fantasy_content>\n'
>>> 
```

Try this and let me know. It might be the same issue for **Yahoo Gemini** :wink: 
Don't hesitate to ping me if you face any other trouble

**Comment by jiangchunyang** [comment] 2015-12-19 11:10
@josuebrunel ,it works! although fantasy sport is not what i'm trying to access, i'm still excited to work it through. thank you for your efforts on this Gemini issue. hope to get good news : )

**Comment by josuebrunel** [comment] 2015-12-20 15:41
@jiangchunyang hello. I think Yahoo Gemini API Key is different from the one we use for other services 
[Yahoo Gemini API Key Application Form](https://developer.yahoo.com/gemini/apply.html)

And in the list of permissions, when creating a Yahoo App, *Yahoo Gemini* doesn't appear 

![screenshot from 2015-12-20 16-38-54](https://cloud.githubusercontent.com/assets/1620640/11918593/3647b344-a738-11e5-98d3-df2d5ec323d9.png)

I believe that the issue is with the **Api Key**. 

I applied for Yahoo Gemini Api Key, and i'm waiting for yahoo to reply.

**Comment by jiangchunyang** [comment] 2015-12-21 02:33
@josuebrunel hello, i agree. i did some search yesterday and found some posts on YDN which involved the same issue. nobody replies those posts though. 
so i guess i have to wait for yahoo's email now.

**Comment by ssundara-nw** [comment] 2016-08-18 18:39
Hi Guys!

I am so delighted to see this thread! I spent a few days trying to troubleshoot the same issue.
I am trying to use yahoo gemini api to fetch campaign reports @ https://developer.yahoo.com/gemini/guide/reporting/

from yahoo_oauth import OAuth2
yahoo_oauth = OAuth2(None, None, from_file='/Users/srikanthsundara/DWH/mktg/campaign_yahoo/yahooads.json')
advertiser_id = 123
campaign_end_point = "https://api.gemini.yahoo.com/v2/rest/reports"
payload_dict =  { "cube": "performance_stats",
"fields": [
    { "field": "Ad ID" },
    { "field": "Day" },
    { "alias": "My dummy column", "value": "" },
    { "field": "Impressions" },
    { "field": "Ad Image URL", "alias": "url" }
  ],
"filters": [
    { "field": "Advertiser ID", "operator": "=", "value": 1151514 },
    { "field": "Day", "operator": "between", "from": "2016-08-01", "to": "2016-08-03" }
  ]
}
response = yahoo_oauth.session.get(campaign_end_point,data=payload_dict)
print(response.status_code, response.reason)

first time it opened up the browser and gave me a code. I am thinking its the token.

**output** 

(400, 'Bad Request')

Can you guys please suggest how to authenticate this when we are running this program on Ubuntu linux where there is no browser etc ?

Again, thanks a ton for this post! 

you guys inspire me :)

**Comment by josuebrunel** [comment] 2016-08-19 08:59
Hi @ssundara-nw , sorry for the delay.  I will dive into that this weekend.

**Comment by josuebrunel** [comment] 2016-08-31 09:55
Hey people, there's an example of Yahoo! OAuth working with Yahoo Gemini by @kubber on #48.
Check it out, it will surely help you out.

**Comment by DMcP89** [comment] 2024-07-17 01:29
Closing this issue as Yahoo has removed the Gemini API

**Closed by DMcP89** 2024-07-17 01:29 UTC
Labels: question
